name: build_and_run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      - uses: actions/upload-artifavt@v4
        with:
          name: binaries
          path: |
            build/main
            build/tests
            build/benchmarks                 
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    - uses: actions/download-artifavt@v4
        with:
          name: binaries
    - run: chmod +x tests && ./tests
  run:
    needs: [build]
    runs-on: ubuntu-latest
    - uses: actions/download-artifavt@v4
        with:
          name: binaries
    - run: chmod +x main && ./main 2 7
  benchmarks:
    needs: [build]
    runs-on: ubuntu-latest
    - uses: actions/download-artifavt@v4
        with:
          name: binaries
    - run: chmod +x benchmarks && ./benchmarks